# Generated by Django 3.2.5 on 2021-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_user_info_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={},
        ),
        migrations.AlterField(
            model_name='user_info',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
