# Generated by Django 3.2.5 on 2021-10-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20211020_0745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
